from aiogram.fsm.state import StatesGroup, State


class SaveSteps(StatesGroup):
    GET_NAME = State()
    GET_VOLTAGE = State()
    GET_COST = State()
    GET_LINK = State()
    GET_CATEGORY_1LVL = State()
    GET_CATEGORY_2LVL = State()
    GET_ACTIVITY = State()
    GET_SEARCH = State()
    GET_DELETE = State()
    GET_ACTIVITY_DELETE = State()
    GET_CONFIRM = State()
    SEARCH_NAME = State()
    GET_NEW_NAME = State()
    GET_NEW_NAME2 = State()
    GET_UPDATE = State()
    GET_PASSWORD = State()
    CHECK = State()
    GET_ID = State()
    GET_EDIT = State()
    EDIT_ATTR = State()
    GET_NAME_EDIT = State()
    EDIT_NAME = State()
    GET_VOLTAGE_EDIT = State()
    EDIT_VOLTAGE = State()
    GET_COST_EDIT = State()
    EDIT_COST = State()
    GET_LINK_EDIT = State()
    EDIT_LINK = State()
    GET_PRED_EDIT = State()
    GET_CONFIRM_EDITS = State()
    GET_CATEGORY_LITE1 = State()
    GET_CATEGORY_LITE2 = State()
